import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

import { makeWorkspace as makeTestWorkspace, runCli, snapshotFiles } from './helpers/workspace.mjs';

function makeWorkspace() {
  const workspace = makeTestWorkspace({ prefix: 'ai-agents-readonly-', packageName: 'read-only-test', runtime: true });
  const { root, coordinationRoot } = workspace;
  fs.writeFileSync(path.join(coordinationRoot, 'board.json'), JSON.stringify({
    projectName: 'Read Only Test',
    updatedAt: '2026-01-01T00:00:00.000Z',
    tasks: [
      { id: 'task-active', status: 'active', ownerId: 'agent-1', title: 'Active task', claimedPaths: ['src/a'], updatedAt: '2026-01-01T00:00:00.000Z' },
      { id: 'task-planned', status: 'planned', ownerId: null, title: 'Planned task', claimedPaths: [], updatedAt: '2026-01-01T00:00:00.000Z' },
    ],
  }, null, 2));
  fs.writeFileSync(path.join(coordinationRoot, 'journal.md'), '# Journal\n\n');
  fs.writeFileSync(path.join(coordinationRoot, 'messages.ndjson'), '');
  fs.writeFileSync(path.join(coordinationRoot, 'runtime', 'watcher.status.json'), JSON.stringify({ pid: 99999999, updatedAt: '2000-01-01T00:00:00.000Z' }, null, 2));
  return workspace;
}

function run(root, coordinationRoot, args) {
  return runCli(root, args, { coordinationRoot });
}

const commandsExpectedToSucceed = new Set([
  'summarize',
  'summarize --for-chat',
  'summarize --json',
  'validate --json',
  'doctor --json',
  'status',
  'prompt agent-1',
  'prompt agent-1 --json',
  'ask who owns src/a',
  'ask who owns src/a --json',
  'prioritize task-active --priority high --dry-run',
  'approvals list',
  'changelog',
  'changelog --json',
  'completions bash',
  'completions list --json',
  'heartbeat-status',
  'watch-status',
  'lock-status',
  'lock-status --json',
  'cleanup-runtime',
  'cleanup-runtime --json',
  'repair-board',
  'migrate-board',
  'artifacts list',
  'artifacts prune',
  'graph',
  'ownership-map',
  'ownership-review',
  'ownership-review --json',
  'test-impact',
  'test-impact --json',
  'risk-score',
  'risk-score --json',
  'critical-path',
  'critical-path --json',
  'health-score',
  'health-score --json',
  'agent-history',
  'agent-history --json',
  'runbooks list',
  'runbooks suggest --paths migrations/001.sql --summary migration',
  'runbooks create custom --title Custom --keywords custom --steps Step',
  'path-groups',
  'path-groups --json',
  'split-validate',
  'split-validate --json',
  'escalation-route',
  'escalation-route --json',
  'steal-work agent-2',
  'steal-work agent-2 --json',
  'contracts list',
  'contracts check',
  'contracts create api-contract --owner agent-1 --scope api --summary API contract',
  'github-status',
  'github-status --json',
  'templates list',
  'templates show react',
  'templates apply react',
  'templates create-task docs-only --id task-docs',
  'archive-completed',
  'archive-completed --json',
  'update-coordinator',
  'update-coordinator --json',
  'snapshot-workspace',
  'snapshot-workspace --json',
  'backlog-import',
  'backlog-import --json',
  'pr-summary',
  'migrate-config',
  'compact-state',
  'compact-state --json',
  'policy-packs list',
  'policy-packs apply strict-ui',
  'policy-check',
  'rollback-state --list',
  'rollback-state --list --json',
]);

for (const args of [
  ['summarize'],
  ['summarize', '--for-chat'],
  ['summarize', '--json'],
  ['validate', '--json'],
  ['doctor', '--json'],
  ['status'],
  ['prompt', 'agent-1'],
  ['prompt', 'agent-1', '--json'],
  ['ask', 'who owns src/a'],
  ['ask', 'who owns src/a', '--json'],
  ['prioritize', 'task-active', '--priority', 'high', '--dry-run'],
  ['approvals', 'list'],
  ['approvals', 'check', 'task-active'],
  ['changelog'],
  ['changelog', '--json'],
  ['completions', 'bash'],
  ['completions', 'list', '--json'],
  ['pick'],
  ['inbox'],
  ['heartbeat-status'],
  ['watch-status'],
  ['lock-status'],
  ['lock-status', '--json'],
  ['watch-diagnose'],
  ['watch-diagnose', '--json'],
  ['cleanup-runtime'],
  ['cleanup-runtime', '--json'],
  ['inspect-board'],
  ['inspect-board', '--json'],
  ['repair-board'],
  ['migrate-board'],
  ['release-check', '--json'],
  ['artifacts', 'list'],
  ['artifacts', 'prune'],
  ['graph'],
  ['ownership-map'],
  ['branches'],
  ['branches', '--json'],
  ['ownership-review'],
  ['ownership-review', '--json'],
  ['test-impact'],
  ['test-impact', '--json'],
  ['risk-score'],
  ['risk-score', '--json'],
  ['critical-path'],
  ['critical-path', '--json'],
  ['health-score'],
  ['health-score', '--json'],
  ['agent-history'],
  ['agent-history', '--json'],
  ['runbooks', 'list'],
  ['runbooks', 'suggest', '--paths', 'migrations/001.sql', '--summary', 'migration'],
  ['runbooks', 'create', 'custom', '--title', 'Custom', '--keywords', 'custom', '--steps', 'Step'],
  ['path-groups'],
  ['path-groups', '--json'],
  ['split-validate'],
  ['split-validate', '--json'],
  ['escalation-route'],
  ['escalation-route', '--json'],
  ['steal-work', 'agent-2'],
  ['steal-work', 'agent-2', '--json'],
  ['contracts', 'list'],
  ['contracts', 'check'],
  ['contracts', 'create', 'api-contract', '--owner', 'agent-1', '--scope', 'api', '--summary', 'API contract'],
  ['github-status'],
  ['github-status', '--json'],
  ['templates', 'list'],
  ['templates', 'show', 'react'],
  ['templates', 'apply', 'react'],
  ['templates', 'create-task', 'docs-only', '--id', 'task-docs'],
  ['archive-completed'],
  ['archive-completed', '--json'],
  ['update-coordinator'],
  ['update-coordinator', '--json'],
  ['snapshot-workspace'],
  ['snapshot-workspace', '--json'],
  ['backlog-import'],
  ['backlog-import', '--json'],
  ['pr-summary'],
  ['release-bundle', '--out-dir', 'bundle'],
  ['migrate-config'],
  ['compact-state'],
  ['compact-state', '--json'],
  ['policy-packs', 'list'],
  ['policy-packs', 'apply', 'strict-ui'],
  ['policy-check'],
  ['rollback-state', '--list'],
  ['rollback-state', '--list', '--json'],
]) {
  test(`${args.join(' ')} does not mutate coordination state`, () => {
    const { root, coordinationRoot } = makeWorkspace();
    const files = [
      path.join(coordinationRoot, 'board.json'),
      path.join(coordinationRoot, 'journal.md'),
      path.join(coordinationRoot, 'messages.ndjson'),
      path.join(coordinationRoot, 'runtime', 'watcher.status.json'),
    ];
    const before = snapshotFiles(files);
    const result = run(root, coordinationRoot, args);
    const after = snapshotFiles(files);

    if (commandsExpectedToSucceed.has(args.join(' '))) {
      assert.equal(result.status, 0, result.stderr);
    }
    assert.deepEqual(after, before);
  });
}
